### ISSUE TITLE
Chain Unauthorized exceptions 

### ISSUE THREAD

**Issue by etagwerker** [ombulabs/bitpagos#3]
We should look into this https://github.com/ombulabs/bitpagos/pull/2#discussion_r48661112

**Comment by mauro-oto** [comment]
@etagwerker I've been looking into this, I'm not quite sure how to implement it because we do not have a logger. I did come across this while testing something unrelated: 

```ruby
4) Bitpagos::Client#transaction_count returns the transaction count
     Failure/Error: raise Bitpagos::Errors::Unauthorized.new(error.message)
     
     Bitpagos::Errors::Unauthorized:
       401 Unauthorized
     # ./lib/bitpagos/client.rb:79:in `rescue in retrieve_transactions'
     # ./lib/bitpagos/client.rb:75:in `retrieve_transactions'
     # ./lib/bitpagos/client.rb:31:in `transactions'
     # ./lib/bitpagos/client.rb:54:in `transaction_count'
     # ./spec/bitpagos/client_spec.rb:85:in `block (4 levels) in <top (required)>'
     # /Users/mauro-oto/.rvm/gems/ruby-2.2.1@bitpagos-gem/gems/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call'
     # /Users/mauro-oto/.rvm/gems/ruby-2.2.1@bitpagos-gem/gems/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /Users/mauro-oto/.rvm/gems/ruby-2.2.1@bitpagos-gem/gems/vcr-2.9.3/lib/vcr.rb:182:in `use_cassette'
     # ./spec/bitpagos/client_spec.rb:84:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # RestClient::Unauthorized:
     #   401 Unauthorized
     #   /Users/mauro-oto/.rvm/gems/ruby-2.2.1@bitpagos-gem/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
```

It printed the cause right there in the exception by default, I'm not sure if that's RSpec behavior or some Ruby default.

**Comment by etagwerker** [comment]
@mauro-oto My bad. In the latest version of Ruby (>2.1) this is done implicitly, no need to set the cause explicitly. More info here: http://devblog.avdi.org/2013/12/25/exception-causes-in-ruby-2-1/
